### ISSUE TITLE
libcstring missing autogen.ps1

### ISSUE THREAD

**Issue by SammyB428** [libyal/libcstring#1]
Windows won't compile from a virgin download.

**Comment by joachimmetz** [comment]
With `Windows` I assume you mean Visual Studio? Since Cygwin and MinGW-MSYS are also Windows build environments and would use `autogen.sh`.

I do not consider this an issue. If you want a Visual Studio build follow the instructions and get a source package instead. Also see: https://github.com/libyal/libcstring/wiki/Building#using-microsoft-visual-studio

Both `autogen.ps1` and `synclibs.ps1` have been recently been added to libyal projects for testing on AppVeyor. For  libcstring this has not been done yet. You can always copy `synclibs.ps1` from another libyal project.
